all:
  children:
    kubernetes:
      children:
        application_nodes:
          hosts:
            application-instance:
              ansible_host: localhost
              instance_id: "i-0762c736d015cce69"
              private_ip: "10.0.20.81"
              instance_type: application
              deploy_database: true
        monitoring_nodes:
          hosts:
            monitoring-instance:
              ansible_host: localhost
              instance_id: "i-0335e1259c4a16ed2"
              private_ip: "10.0.10.103"
              instance_type: monitoring
              deploy_database: false
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    aws_region: eu-central-1
    project_name: "{{ project_name | default('devops-infra') }}"
    deployment_environment: "{{ deployment_environment | default('dev') }}" 